name: CI

on: [push]

jobs:
  sast_scan:
    name: Rub Bandit Scan
    runs-on: Ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: set uo Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r .
    
