name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Static Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit.json

    - name: Upload Bandit Findings
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit.json

  image_scan:
    name: Build and Scan Docker Imaged
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with: 
        docker_version: '20.10.7'

    - name: Build Docker Image
      run: docker build -f Dockerfile -t myapp:latest .

    - name: Install Docker Scout
      run: |
        curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        sh install-scout.sh
        docker scout quickview 
        docker scout cves
